# ---- init wizard --------------------------------------------------------
#
# Authored here; build.sh inlines this region into the single `subgrove`
# script. Edit THIS file, then run ./build.sh to sync. Never sourced at
# runtime — it is inlined, so it reuses err/info/list_all_submodules/
# discover_root and the WORKTREES_DIR/BUILD_*/BRANCH_PREFIX defaults from
# the parent script directly.

# _init_prompt VAR "Question" "default"
# Reads a line into VAR, falling back to the default on empty input. In
# non-interactive mode (--defaults or non-TTY stdin) it takes the default
# without prompting. printf -v is bash 3.1+, fine on macOS bash 3.2. The
# caller's $_init_noninteractive is visible here via bash dynamic scope.
_init_prompt() {
    local __q="$2" __def="$3" __ans
    if [[ "$_init_noninteractive" == "true" ]]; then
        printf -v "$1" '%s' "$__def"
        return
    fi
    printf '  %s [%s]: ' "$__q" "$__def" >&2
    IFS= read -r __ans || __ans=""
    [[ -z "$__ans" ]] && __ans="$__def"
    printf -v "$1" '%s' "$__ans"
}

# _init_emit_array NAME ELEMENTS...  -> prints `NAME=("e1" "e2")` (or `NAME=()`)
_init_emit_array() {
    local name="$1"; shift
    printf '%s=(' "$name"
    local first=true e
    for e in "$@"; do
        if [[ "$first" == "true" ]]; then first=false; else printf ' '; fi
        printf '"%s"' "$e"
    done
    printf ')\n'
}

# _init_split CSV_OR_WS  -> emits tokens space-separated (comma or whitespace
# input); "none"/empty yields nothing. Caller word-splits the result.
_init_split() {
    local v="$1"
    [[ "$v" == "none" || -z "$v" ]] && return 0
    printf '%s' "$v" | tr ',' ' '
}

cmd_init() {
    discover_root          # sets ROOT; sources an existing .subgroverc as defaults
    cd "$ROOT"

    local _init_noninteractive=false
    case "${1:-}" in
        -y|--yes|--defaults) _init_noninteractive=true ;;
    esac
    [[ -t 0 ]] || _init_noninteractive=true   # piped/CI stdin: never block on a prompt

    local rc="$ROOT/.subgroverc"
    if [[ -f "$rc" ]]; then
        info "Reconfiguring — current values shown as [defaults]; Enter keeps them"
    else
        info "Setting up .subgroverc for this superproject"
    fi

    # 1. Branch prefix.
    _init_prompt BRANCH_PREFIX "Feature branch prefix" "$BRANCH_PREFIX"

    # 2. Build chain — offer the detected submodules by name.
    local detected=() sm
    while IFS= read -r sm; do
        [[ -n "$sm" ]] && detected+=("$sm")
    done < <(list_all_submodules 2>/dev/null)
    if [[ ${#detected[@]} -eq 0 ]]; then
        info "No submodules detected (.gitmodules absent or empty) — BUILD_CHAIN left empty"
        BUILD_CHAIN=()
    else
        info "Detected submodules: ${detected[*]}"
        local _chain_def="${BUILD_CHAIN[*]}" _chain_ans tok
        _init_prompt _chain_ans "Submodules to build on 'new' (space-separated, or 'none')" "$_chain_def"
        BUILD_CHAIN=()
        for tok in $(_init_split "$_chain_ans"); do
            BUILD_CHAIN+=("$tok")
        done
    fi

    # 3. Build command — only meaningful when there's a chain to build.
    if [[ ${#BUILD_CHAIN[@]} -gt 0 ]]; then
        _init_prompt BUILD_CMD "Build command run inside each BUILD_CHAIN module" "$BUILD_CMD"
    fi

    # 4. Files/dirs copied into each new worktree.
    local _copy_def="${COPY_TO_NEW_WORKTREE[*]}" _copy_ans citem
    _init_prompt _copy_ans "Files/dirs copied into each new worktree (space-separated, or 'none')" "$_copy_def"
    COPY_TO_NEW_WORKTREE=()
    for citem in $(_init_split "$_copy_ans"); do
        COPY_TO_NEW_WORKTREE+=("$citem")
    done

    # Write .subgroverc, backing up any existing one first.
    if [[ -f "$rc" ]]; then
        cp "$rc" "$rc.bak"
        info "Backed up existing .subgroverc to .subgroverc.bak"
    fi
    {
        echo "# subgrove configuration — generated by 'subgrove init'."
        echo "# Sourced by subgrove from the superproject root. See"
        echo "# .subgroverc.example for the full schema and notes."
        echo
        echo "# Ordered submodule paths to build during 'new' (empty = no auto-build)."
        _init_emit_array BUILD_CHAIN "${BUILD_CHAIN[@]}"
        echo
        echo "# Shell command run inside each BUILD_CHAIN module."
        printf 'BUILD_CMD="%s"\n' "$BUILD_CMD"
        echo
        echo "# Files/dirs under the main worktree copied into each new worktree."
        _init_emit_array COPY_TO_NEW_WORKTREE "${COPY_TO_NEW_WORKTREE[@]}"
        echo
        echo "# Feature branch prefix (include the trailing separator, e.g. \"feat/\")."
        printf 'BRANCH_PREFIX="%s"\n' "$BRANCH_PREFIX"
    } > "$rc"
    info "Wrote $rc"

    # Ensure .worktree/ is gitignored AND present on disk: subgrove's
    # `git check-ignore -q .worktree` matches the trailing-slash pattern only
    # when the directory actually exists.
    if ! git check-ignore -q "$WORKTREES_DIR" 2>/dev/null; then
        local _gi_ans
        if [[ "$_init_noninteractive" == "true" ]]; then
            _gi_ans="y"
        else
            printf '  %s/ must be gitignored for subgrove to run. Add it now? [Y/n]: ' "$WORKTREES_DIR" >&2
            IFS= read -r _gi_ans || _gi_ans="y"
        fi
        case "$_gi_ans" in
            ""|y|Y|yes|Yes)
                printf '%s/\n' "$WORKTREES_DIR" >> "$ROOT/.gitignore"
                git add .gitignore 2>/dev/null || true
                info "Added $WORKTREES_DIR/ to .gitignore (staged)"
                ;;
            *)
                info "Left .gitignore alone — subgrove refuses to run until $WORKTREES_DIR/ is ignored"
                ;;
        esac
    fi
    mkdir -p "$ROOT/$WORKTREES_DIR"

    cat <<EOF

subgrove is configured for $ROOT
  Config: $rc
  Next:   subgrove new <feature>
EOF
}
